services:
  mysql:
    image: mysql:8.0
    container_name: loja_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loja_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/sql/loja.sql:/docker-entrypoint-initdb.d/loja.sql

  app:
    build: .
    container_name: loja_app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
      
volumes:
  mysql_data:
